"""Assemble Confluence storage-format HTML for the child page."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any


def build_page(sections: list[dict], chart_files: dict[str, Path]) -> str:
    """Build the full page HTML.

    sections: [{name, metrics: [{name, title, description, chart_path, summary, target}]}]
    chart_files: {metric_name: Path} — for attachment references
    """
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    parts = [
        f'<p><strong>Last updated:</strong> {timestamp} · Auto-generated by metrics-master pipeline</p>',
        '<p><em>For raw ticket details, see sibling pages: Delivery Metrics, IDDs Metrics, Closed Emulations.</em></p>',
        "<hr/>",
    ]

    for section in sections:
        parts.append(f'<h2>{section["name"]}</h2>')

        for metric in section.get("metrics", []):
            parts.append(f'<h3>{metric["title"]}</h3>')
            parts.append(f'<p>{metric.get("description", "")}</p>')

            chart_path = chart_files.get(metric["name"])
            if chart_path:
                filename = chart_path.name
                parts.append(
                    f'<ac:image ac:width="600">'
                    f'<ri:attachment ri:filename="{filename}"/>'
                    f'</ac:image>'
                )

            summary = metric.get("summary")
            if summary:
                parts.append(f"<p><strong>{summary}</strong></p>")

            target = metric.get("target")
            rag = metric.get("rag")
            if target is not None and rag:
                color = {"green": "Green", "amber": "Yellow", "red": "Red"}.get(rag, "Grey")
                parts.append(
                    f'<ac:structured-macro ac:name="status">'
                    f'<ac:parameter ac:name="colour">{color}</ac:parameter>'
                    f'<ac:parameter ac:name="title">Target: {target}</ac:parameter>'
                    f'</ac:structured-macro>'
                )

            parts.append("<hr/>")

    return "\n".join(parts)
