"""Assemble Confluence storage-format HTML for the child page."""

from __future__ import annotations

import urllib.parse
from datetime import datetime
from pathlib import Path
from typing import Any


SIDE_BY_SIDE_SECTIONS = {"Emulation Coverage", "Intake vs Output", "Team Output"}
FULL_WIDTH_SECTIONS = {"Team Velocity"}

SECTION_DESCRIPTIONS = {
    "Emulation Coverage": (
        "This chart displays the number of CVE or Light Cycle emulations covered each week. "
        "It provides a week-over-week view of emulation activity, helping the team track "
        "workload trends and identify periods of increased demand."
    ),
    "Intake vs Output": (
        "This area chart compares the number of CVE or Light Cycle emulations created (red line) "
        "versus resolved (green line) on a weekly basis over the last 30 days. The overlapping "
        "shaded area highlights the gap between creation and resolution; a larger red area indicates "
        "a backlog building up, while a larger green area signals that the team is resolving more "
        "than being created."
    ),
    "Team Output": (
        "Left: weekly IDD creation trend (stacked by completion status). "
        "Right: total IDD distribution by current status across all teams."
    ),
    "Team Velocity": (
        "This chart tracks the team’s <strong>weekly completion velocity</strong> for CVE and Light Cycle "
        "emulations over the last 8 intervals. The purple bars represent the number of emulations completed "
        "in each weekly interval, while the orange trend line shows the average velocity across the last "
        "8 intervals, providing a smoothed view of the team’s delivery pace."
    ),
}

SECTION_TITLES = {
    "Intake vs Output": "Emulations - Created vs. Resolved (Weekly)",
    "Team Output": "Weekly Intel-Driven Detections (IDDs)",
    "Team Velocity": "Team Velocity (Weekly)",
}

SECTION_HEADER_COLORS = {
    "Team Velocity": "#fdf6e3",
}

COLUMN_COLORS = ["#dce6f1", "#e8daf1"]

SECTION_TABLES = {
    "Team Output": {
        "title": "IDD Details",
        "jql": 'project = "Integration, Detection, & Response" AND type in ("Detection Request", "Focus Detection Request") AND labels in (ATDT_IDD) ORDER BY created DESC, Rank ASC',
        "columns": "key,summary,status,created,assignee",
        "max_issues": 5,
    },
}

JIRA_BASE = "https://arcticwolf.atlassian.net"

COLUMN_TABLES = {
    "cve_weekly_coverage": {
        "title": "CVE Details",
        "jql": 'project = "Threat Research and Development" AND labels = ATDT_CVE AND issuetype = Story AND created >= -35d ORDER BY created DESC',
        "columns": "key,summary,status,created,assignee",
        "max_issues": 5,
    },
    "lc_weekly_coverage": {
        "title": "Light Cycle Details",
        "jql": 'project = "Threat Research and Development" AND labels = LightCycles AND issuetype = Story AND created >= -35d ORDER BY created DESC',
        "columns": "key,summary,status,created,assignee",
        "max_issues": 5,
    },
}


def build_page(sections: list[dict], chart_files: dict[str, Path]) -> str:
    """Build the full page HTML.

    sections: [{name, metrics: [{name, title, description, chart_path, summary, target}]}]
    chart_files: {metric_name: Path} — for attachment references
    """
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    parts = [
        '<table style="width: 100%; border: none; border-collapse: collapse;"><tr><td style="padding: 0; border: none;">',
        f'<p><strong>Last updated:</strong> {timestamp} · Auto-generated by metrics-master pipeline</p>',
        '<p><em>For raw ticket details, see sibling pages: Delivery Metrics, IDDs Metrics, Closed Emulations.</em></p>',
        '</td></tr></table>',
        "<hr/>",
    ]

    for section in sections:
        section_name = section["name"]
        metrics = section.get("metrics", [])

        if section_name in SIDE_BY_SIDE_SECTIONS and len(metrics) >= 1:
            parts.append(_build_side_by_side_section(section_name, metrics, chart_files))
        elif section_name in FULL_WIDTH_SECTIONS and len(metrics) >= 1:
            parts.append(_build_full_width_section(section_name, metrics, chart_files))
        else:
            parts.append(f'<h2>{section_name}</h2>')
            for metric in metrics:
                parts.append(_build_metric_block(metric, chart_files))

    return "\n".join(parts)


def _build_side_by_side_section(section_name: str, metrics: list[dict], chart_files: dict[str, Path]) -> str:
    """Render a section with a header band and two-column side-by-side layout."""
    desc = SECTION_DESCRIPTIONS.get(section_name, "")
    display_title = SECTION_TITLES.get(section_name, section_name)

    header_band = (
        f'<table style="width: 100%; border: none; border-collapse: collapse;"><tr>'
        f'<td style="background-color: #f0f0f0; padding: 12px 16px; border: none; border-radius: 4px;">'
        f'<p style="margin: 0; font-size: 18px;"><strong>{display_title}</strong></p>'
        f'<p style="margin: 4px 0 0 0; font-size: 13px; color: #555;">{desc}</p>'
        f'</td></tr></table>'
    )

    columns = []
    for i, metric in enumerate(metrics[:2]):
        col_color = COLUMN_COLORS[i % len(COLUMN_COLORS)]
        col_header = (
            f'<div style="background-color: {col_color}; padding: 8px 12px; border-radius: 3px; margin-bottom: 8px;">'
            f'<strong>{metric["title"]}</strong>'
            f'</div>'
        )
        chart_path = chart_files.get(metric["name"])
        chart_html = ""
        if chart_path:
            chart_html = (
                f'<ac:image ac:width="700">'
                f'<ri:attachment ri:filename="{chart_path.name}"/>'
                f'</ac:image>'
            )

        col_table = ""
        col_table_config = COLUMN_TABLES.get(metric["name"])
        if col_table_config:
            col_table = _build_column_table(col_table_config)

        columns.append(f'{col_header}{chart_html}{col_table}')

    if len(columns) >= 2:
        table = (
            f'<table style="width: 100%; border-collapse: collapse;">'
            f'<tr>'
            f'<td style="width: 49%; vertical-align: top; padding: 8px 16px 8px 8px;">{columns[0]}</td>'
            f'<td style="width: 49%; vertical-align: top; padding: 8px 8px 8px 16px; border-left: 1px solid #ccc;">{columns[1]}</td>'
            f'</tr>'
            f'</table>'
        )
    else:
        table = (
            f'<table style="width: 100%; border-collapse: collapse;">'
            f'<tr>'
            f'<td style="width: 49%; vertical-align: top; padding: 8px 16px 8px 8px;">{columns[0]}</td>'
            f'<td style="width: 49%; vertical-align: top; padding: 8px;"></td>'
            f'</tr>'
            f'</table>'
        )

    result = f'{header_band}\n{table}'

    table_config = SECTION_TABLES.get(section_name)
    if table_config:
        result += _build_jira_table(table_config)

    result += '\n<hr/>'
    return result


def _build_full_width_section(section_name: str, metrics: list[dict], chart_files: dict[str, Path]) -> str:
    """Render a full-width section with header band and single chart."""
    desc = SECTION_DESCRIPTIONS.get(section_name, "")
    display_title = SECTION_TITLES.get(section_name, section_name)
    bg_color = SECTION_HEADER_COLORS.get(section_name, "#f0f0f0")

    header_band = (
        f'<table style="width: 100%; border: none; border-collapse: collapse;"><tr>'
        f'<td style="background-color: {bg_color}; padding: 12px 16px; border: none; border-radius: 4px;">'
        f'<p style="margin: 0; font-size: 18px;"><strong>{display_title}</strong></p>'
        f'<p style="margin: 4px 0 0 0; font-size: 13px; color: #555;">{desc}</p>'
        f'</td></tr></table>'
    )

    chart_parts = []
    for metric in metrics[:1]:
        chart_path = chart_files.get(metric["name"])
        if chart_path:
            chart_parts.append(
                f'<ac:image ac:width="1000">'
                f'<ri:attachment ri:filename="{chart_path.name}"/>'
                f'</ac:image>'
            )

    return f'{header_band}\n{"".join(chart_parts)}\n<hr/>'


def _build_column_table(config: dict) -> str:
    """Render a per-column Jira Issues macro with a 'View all in Jira' link."""
    title = config["title"]
    jql = config["jql"]
    columns = config["columns"]
    max_issues = config.get("max_issues", 5)

    jira_search_url = f'{JIRA_BASE}/issues/?jql={urllib.parse.quote(jql)}'

    table_header = (
        f'<div style="background-color: #e8f4e8; padding: 6px 10px; border-radius: 3px; margin-top: 12px;">'
        f'<strong>{title}</strong>'
        f'</div>'
    )

    jira_macro = (
        f'<ac:structured-macro ac:name="jira">'
        f'<ac:parameter ac:name="jqlQuery">{jql}</ac:parameter>'
        f'<ac:parameter ac:name="columns">{columns}</ac:parameter>'
        f'<ac:parameter ac:name="maximumIssues">{max_issues}</ac:parameter>'
        f'</ac:structured-macro>'
    )

    view_all_link = (
        f'<p style="margin-top: 4px; font-size: 13px;">'
        f'<a href="{jira_search_url}">View all in Jira &rarr;</a>'
        f'</p>'
    )

    return f'{table_header}{jira_macro}{view_all_link}'


def _build_jira_table(config: dict) -> str:
    """Render a Confluence Jira Issues macro — shows N rows with a link to Jira for more."""
    import urllib.parse
    title = config["title"]
    jql = config["jql"]
    columns = config["columns"]
    max_issues = config.get("max_issues", 5)

    jira_search_url = f'{JIRA_BASE}/issues/?jql={urllib.parse.quote(jql)}'

    table_header = (
        f'<table style="width: 100%; border: none; border-collapse: collapse; margin-top: 16px;"><tr>'
        f'<td style="background-color: #e8f4e8; padding: 8px 12px; border: none; border-radius: 3px;">'
        f'<strong>{title}</strong>'
        f'</td></tr></table>'
    )

    jira_macro = (
        f'<ac:structured-macro ac:name="jira">'
        f'<ac:parameter ac:name="jqlQuery">{jql}</ac:parameter>'
        f'<ac:parameter ac:name="columns">{columns}</ac:parameter>'
        f'<ac:parameter ac:name="maximumIssues">{max_issues}</ac:parameter>'
        f'</ac:structured-macro>'
    )

    view_all_link = (
        f'<p style="margin-top: 4px; font-size: 13px;">'
        f'<a href="{jira_search_url}">View all in Jira &rarr;</a>'
        f'</p>'
    )

    return f'\n{table_header}\n{jira_macro}\n{view_all_link}'


def _build_metric_block(metric: dict, chart_files: dict[str, Path]) -> str:
    """Render a single metric block (title, chart, summary, target)."""
    parts = []
    parts.append(f'<h3>{metric["title"]}</h3>')
    parts.append(f'<p>{metric.get("description", "")}</p>')

    chart_path = chart_files.get(metric["name"])
    if chart_path:
        parts.append(
            f'<ac:image ac:width="600">'
            f'<ri:attachment ri:filename="{chart_path.name}"/>'
            f'</ac:image>'
        )

    summary = metric.get("summary")
    if summary:
        parts.append(f"<p><strong>{summary}</strong></p>")

    target = metric.get("target")
    rag = metric.get("rag")
    if target is not None and rag:
        color = {"green": "Green", "amber": "Yellow", "red": "Red"}.get(rag, "Grey")
        parts.append(
            f'<ac:structured-macro ac:name="status">'
            f'<ac:parameter ac:name="colour">{color}</ac:parameter>'
            f'<ac:parameter ac:name="title">Target: {target}</ac:parameter>'
            f'</ac:structured-macro>'
        )

    parts.append("<hr/>")
    return "\n".join(parts)
