"""Assemble Confluence storage-format HTML for the per-quarter summary report page."""

from __future__ import annotations

import html
from datetime import datetime
from typing import Any

JIRA_BASE = "https://arcticwolf.atlassian.net"


def build_quarterly_report_page(quarter_label: str, section_data: dict[str, Any]) -> str:
    """Build the full Quarterly Metrics Summary page HTML.

    section_data: {"light_cycles": {...}, "cves": {...}, "research_projects": {...}}
    — light_cycles/cves shaped {total_*, total_idds, rows: [{seq, key, summary,
    status, confluence_page, poc_impact, linked_idds}]} (compute_light_cycles_section
    / compute_cve_section); research_projects shaped {total_research_projects,
    rows: [{seq, key, summary, status, confluence_page, excerpt}]}
    (compute_research_projects_section).
    """
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    # Confluence's renderer caps plain <p>/<h*> elements to a "readable" column
    # width even on a full-width page — only elements like tables span the full
    # container. Wrapping every text block in its own width:100% table cell (the
    # same trick page_builder.py already uses) forces headings and stat lines to
    # stretch edge-to-edge like the data table does.
    header = (
        '<table style="width: 100%; border: none; border-collapse: collapse;">'
        '<tr><td style="padding: 0; border: none;">'
        f'<p><strong>Quarter:</strong> {quarter_label} &nbsp;&middot;&nbsp; '
        f'<strong>Last updated:</strong> {timestamp} &nbsp;&middot;&nbsp; '
        f'Auto-generated by metrics-master pipeline</p>'
        '</td></tr></table>'
    )

    category_header = (
        '<table style="width: 100%; border: none; border-collapse: collapse;">'
        '<tr><td style="padding: 0; border: none;"><h2>Work Breakdown by Category</h2></td></tr></table>'
    )

    parts = [
        header,
        '<hr/>',
        category_header,
        _build_category_subsection(
            "Light Cycles & IDDs", "Total Light Cycles",
            section_data.get("light_cycles", {}), "total_light_cycles",
        ),
        _build_category_subsection(
            "CVEs & IDDs", "Total CVEs",
            section_data.get("cves", {}), "total_cves",
        ),
        _build_research_projects_subsection(section_data.get("research_projects", {})),
        _build_metrics_section(section_data.get("tio_response_rate", {})),
    ]

    return "\n".join(parts)


def _build_category_subsection(
    subtitle: str, total_label: str, section_data: dict[str, Any], total_key: str
) -> str:
    total_value = section_data.get(total_key, 0)
    total_idds = section_data.get("total_idds", 0)
    rows = section_data.get("rows", [])

    header_band = (
        '<table style="width: 100%; border: none; border-collapse: collapse;">'
        '<tr><td style="padding: 0; border: none;">'
        f'<h3>{subtitle}</h3>'
        f'<p><strong>{total_label}:</strong> {total_value} '
        f'&nbsp;&nbsp;&nbsp; <strong>Total IDDs:</strong> {total_idds}</p>'
        '</td></tr></table>'
    )

    parts = [header_band]

    if not rows:
        parts.append(
            '<table style="width: 100%; border: none; border-collapse: collapse;">'
            '<tr><td style="padding: 0; border: none;"><p>No Data</p></td></tr></table>'
        )
        return "\n".join(parts)

    table_rows = ['<tr><th>#</th><th>SHLD Story</th><th>Status</th>'
                  '<th>Confluence Page</th><th>POC Impact</th><th>Linked IDDs</th></tr>']

    for row in rows:
        story_link = _issue_link(row["key"], row.get("summary", ""))
        confluence_page = row.get("confluence_page")
        confluence_cell = (
            f'<a href="{confluence_page["url"]}">{confluence_page["title"]}</a>'
            if confluence_page else "&mdash;"
        )
        poc_cell = "X" if row.get("poc_impact") else ""
        idd_links = row.get("linked_idds", [])
        idd_cell = (
            ", ".join(_issue_link(idd["key"], idd.get("summary", "")) for idd in idd_links)
            if idd_links else "&mdash;"
        )

        table_rows.append(
            f'<tr><td>{row["seq"]}</td><td>{story_link}</td><td>{_status_badge(row["status"])}</td>'
            f'<td>{confluence_cell}</td><td>{poc_cell}</td><td>{idd_cell}</td></tr>'
        )

    parts.append(f'<table style="width: 100%;"><tbody>{"".join(table_rows)}</tbody></table>')
    return "\n".join(parts)


def _build_research_projects_subsection(section_data: dict[str, Any]) -> str:
    rows = section_data.get("rows", [])

    header_band = (
        '<table style="width: 100%; border: none; border-collapse: collapse;">'
        '<tr><td style="padding: 0; border: none;"><h3>Research Projects</h3></td></tr></table>'
    )

    parts = [header_band]

    if not rows:
        parts.append(
            '<table style="width: 100%; border: none; border-collapse: collapse;">'
            '<tr><td style="padding: 0; border: none;"><p>No Data</p></td></tr></table>'
        )
        return "\n".join(parts)

    table_rows = ['<tr><th>#</th><th>SHLD Story</th><th>Status</th>'
                  '<th>Confluence Page</th><th>Summary</th></tr>']

    for row in rows:
        story_link = _issue_link(row["key"], row.get("summary", ""))
        confluence_page = row.get("confluence_page")
        confluence_cell = (
            f'<a href="{confluence_page["url"]}">{confluence_page["title"]}</a>'
            if confluence_page else "&mdash;"
        )
        excerpt = row.get("excerpt", "")
        excerpt_cell = html.escape(excerpt) if excerpt else "&mdash;"

        table_rows.append(
            f'<tr><td>{row["seq"]}</td><td>{story_link}</td><td>{_status_badge(row["status"])}</td>'
            f'<td>{confluence_cell}</td><td>{excerpt_cell}</td></tr>'
        )

    parts.append(f'<table style="width: 100%;"><tbody>{"".join(table_rows)}</tbody></table>')
    return "\n".join(parts)


def _issue_link(key: str, summary: str = "") -> str:
    link = f'<a href="{JIRA_BASE}/browse/{key}">{key}</a>'
    return f'{link} — {summary}' if summary else link


def _status_badge(status: str) -> str:
    colour = "Green" if status in ("Done", "In Progress") else "Grey"
    return (
        '<ac:structured-macro ac:name="status" ac:schema-version="1">'
        f'<ac:parameter ac:name="title">{status}</ac:parameter>'
        f'<ac:parameter ac:name="colour">{colour}</ac:parameter>'
        '</ac:structured-macro>'
    )


def _threat_level_badge(level: str) -> str:
    colours = {
        "LOW": "Green",
        "MEDIUM": "Blue",
        "HIGH": "Yellow",
        "CRITICAL": "Red",
        "MEGA": "Red",
    }
    colour = colours.get(level, "Grey")
    return (
        '<ac:structured-macro ac:name="status" ac:schema-version="1">'
        f'<ac:parameter ac:name="title">{level}</ac:parameter>'
        f'<ac:parameter ac:name="colour">{colour}</ac:parameter>'
        '</ac:structured-macro>'
    )


def _build_metrics_section(tio_data: dict[str, Any]) -> str:
    """Build the 'Metrics' H1 section with Light Cycles Goal: Response Rate."""
    metrics_header = (
        '<table style="width: 100%; border: none; border-collapse: collapse;">'
        '<tr><td style="padding: 0; border: none;"><h1>Metrics</h1></td></tr></table>'
    )

    total = tio_data.get("total_thread_events", 0)
    covered = tio_data.get("atdt_emulations", 0)
    rate = tio_data.get("response_rate", 0.0)
    rows = tio_data.get("rows", [])

    stats_band = (
        '<table style="width: 100%; border: none; border-collapse: collapse;">'
        '<tr><td style="padding: 0; border: none;">'
        '<h3>Light Cycles Goal: Response Rate</h3>'
        f'<p><strong>Total Thread Events:</strong> {total} '
        f'&nbsp;&nbsp;&nbsp; <strong>ATDT Emulation:</strong> {covered} '
        f'&nbsp;&nbsp;&nbsp; <strong>% Response Rate:</strong> {rate}%</p>'
        '</td></tr></table>'
    )

    parts = [metrics_header, stats_band]

    if not rows:
        parts.append(
            '<table style="width: 100%; border: none; border-collapse: collapse;">'
            '<tr><td style="padding: 0; border: none;">'
            '<p>No qualifying TIO Tippers found for this quarter.</p>'
            '</td></tr></table>'
        )
        return "\n".join(parts)

    table_rows = [
        '<tr>'
        '<th>#</th>'
        '<th>TIO TIPPER</th>'
        '<th>Threat Level</th>'
        '<th>Link</th>'
        '<th>ATDT Coverage</th>'
        '<th>Key Samples for Reproduction</th>'
        '</tr>'
    ]

    for row in rows:
        title_esc = html.escape(row["title"])
        url = row.get("url", "")
        threat_level = row.get("threat_level", "")
        samples_info = html.escape(row.get("samples_info", ""))
        has_samples = row.get("has_samples", False)
        samples_badge = (
            '<ac:structured-macro ac:name="status" ac:schema-version="1">'
            '<ac:parameter ac:name="title">COUNTED</ac:parameter>'
            '<ac:parameter ac:name="colour">Green</ac:parameter>'
            '</ac:structured-macro> '
            if has_samples else
            '<ac:structured-macro ac:name="status" ac:schema-version="1">'
            '<ac:parameter ac:name="title">NOT COUNTED</ac:parameter>'
            '<ac:parameter ac:name="colour">Grey</ac:parameter>'
            '</ac:structured-macro> '
        )

        link_cell = f'<a href="{url}">{title_esc}</a>' if url else title_esc

        coverage = row.get("coverage")
        if coverage and coverage.get("confluence_page"):
            cp = coverage["confluence_page"]
            coverage_cell = f'<a href="{cp["url"]}">{html.escape(cp["title"])}</a>'
        elif coverage:
            coverage_cell = _issue_link(coverage["key"], coverage.get("summary", ""))
        else:
            coverage_cell = "&mdash;"

        table_rows.append(
            f'<tr>'
            f'<td>{row["seq"]}</td>'
            f'<td>{title_esc}</td>'
            f'<td>{_threat_level_badge(threat_level)}</td>'
            f'<td>{link_cell}</td>'
            f'<td>{coverage_cell}</td>'
            f'<td>{samples_badge}{samples_info}</td>'
            f'</tr>'
        )

    table_html = (
        f'<table style="width: 100%;"><tbody>{"".join(table_rows)}</tbody></table>'
    )

    expand_html = (
        '<ac:structured-macro ac:name="expand" ac:schema-version="1">'
        '<ac:parameter ac:name="title">'
        'TIO Tippers Details (click to expand)</ac:parameter>'
        '<ac:rich-text-body>'
        f'{table_html}'
        '</ac:rich-text-body>'
        '</ac:structured-macro>'
    )

    parts.append(expand_html)
    return "\n".join(parts)
